version: "3.8"
services:
  api-min:
    profiles: ["prod"]
    image: ghcr.io/holmes89/hello-api:min
    ports:
      - 8080:8080
    build: .
  api-dev:
    profiles: ["dev"]
    image: ghcr.io/holmes89/hello-api:dev
    ports:
      - 8080:8080
    build:
      context: .
      target: dev
