name: CI Checks

on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test App
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.22
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Downloads
        run: go get -t ./...
      - name: Test
        run: make test
      - name: Coverage Check
        run: make coverage
      - name: Generate Report
        run: make report
      - name: Copy Files
        run: |
              mkdir reports
              cp cover.xhtml reports/.
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: reports

  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.22
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Downloads
        run: go get -t ./...
      - name: Build
        run: make build
      - name: Copy Files
        run: |
          mkdir artifacts
          cp api artifacts/.
      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: api
          path: artifacts
